# Generated by Django 4.1.3 on 2022-11-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mintage', models.IntegerField()),
                ('image', models.CharField(max_length=99)),
            ],
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-date']},
        ),
    ]
