# Generated by Django 4.1.3 on 2022-11-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_coin_alter_offer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
