# Generated by Django 4.1.3 on 2022-11-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_coin_image_alter_coin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='coins',
            field=models.ManyToManyField(to='main_app.coin'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
